# Generated by Django 6.0.7 on 2026-08-23 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antojo', '0003_antojodeldia_activo_hasta'),
        ('productos', '0012_presentacioninsumo_presentacion_insumos_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='antojodeldia',
            name='presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.presentacion'),
        ),
    ]
