# Generated by Django 6.0.7 on 2026-07-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="direccion",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="pedido",
            name="telefono",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="pedido",
            name="tipo_entrega",
            field=models.CharField(
                choices=[("retiro", "Retiro en local"), ("delivery", "Delivery")],
                default="retiro",
                max_length=20,
            ),
        ),
    ]
