# Generated by Django 6.0.7 on 2026-07-29 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_pedido_direccion_pedido_telefono_pedido_tipo_entrega"),
        ("productos", "0004_combo"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallepedido",
            name="combo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="productos.combo",
            ),
        ),
        migrations.AlterField(
            model_name="detallepedido",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="productos.producto",
            ),
        ),
    ]
