# Generated by Django 6.0.1 on 2026-07-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0004_localidad_pedido_costo_envio_pedido_descuento_pct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="hora_salida",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
