# Generated by Django 6.0.7 on 2026-08-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0009_detalleextra_cantidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallepedido",
            name="descuento_pct",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
