# Generated by Django 6.0.7 on 2026-08-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0013_caja_dia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="creado",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
