# Generated by Django 6.0.7 on 2026-08-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0014_alter_pedido_creado"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pedido",
            options={"ordering": ["-creado", "-id"]},
        ),
    ]
