# Generated by Django 6.0.7 on 2026-08-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_alter_pedido_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='sugerido_carrito',
            field=models.BooleanField(default=False),
        ),
    ]
