# Generated by Django 6.0.7 on 2026-08-18 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0018_pedido_cliente_registrado_pedido_descuento_puntos_and_more'),
        ('productos', '0010_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.presentacion'),
        ),
    ]
