# Generated by Django 6.0.7 on 2026-08-21 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_recompensa"),
        ("pedidos", "0019_detallepedido_presentacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="recompensa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos",
                to="clientes.recompensa",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="recompensa_nombre",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
