# Generated by Django 6.0.1 on 2026-07-31 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antojo", "0001_initial"),
        ("productos", "0007_alter_combo_productos_alter_producto_insumos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="antojodeldia",
            name="fecha",
        ),
        migrations.RemoveField(
            model_name="antojodeldia",
            name="motivo",
        ),
        migrations.AddField(
            model_name="antojodeldia",
            name="activo",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="antojodeldia",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="productos.producto",
            ),
        ),
    ]
