# Generated by Django 6.0.7 on 2026-08-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "antojo",
            "0002_remove_antojodeldia_fecha_remove_antojodeldia_motivo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="antojodeldia",
            name="activo_hasta",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
