"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Variables de entorno: en local se leen de un archivo .env (no versionado) junto a
# manage.py; en PythonAnywhere se configuran en el panel de la app (ver README/chat).
load_dotenv(BASE_DIR / '.env')


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# SECURITY WARNING: keep the secret key used in production secret!
# El valor de acá abajo es solo un respaldo para que el proyecto no se rompa si falta
# el .env — en producción SIEMPRE tiene que estar seteado DJANGO_SECRET_KEY.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-ww(qv84a)bqrgav_fqesmg(yhod*hy*uhv32=%-spzeq1=#23z',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Por defecto queda APAGADO (seguro) a menos que el .env diga explícitamente lo contrario.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# Los dominios de produccion se cargan del .env (DJANGO_ALLOWED_HOSTS, separados por coma)
# para no tocar codigo al cambiar de servidor.
_hosts = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]
ALLOWED_HOSTS = ['localhost', '127.0.0.1'] + _hosts

# Sin esto el login del admin por https devuelve "CSRF verification failed".
CSRF_TRUSTED_ORIGINS = ['https://' + h for h in _hosts]

# Endurecimiento de seguridad que solo aplica cuando DEBUG está apagado (producción) —
# en local (DEBUG=True) se dejan desactivados para no romper el runserver por http.
if not DEBUG:
    # Detras de nginx, Django ve http en el socket. Sin esta linea SECURE_SSL_REDIRECT
    # entra en loop infinito de redirects. nginx manda el header via proxy_params (ver MIGRACION.md).
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

SECURE_CONTENT_TYPE_NOSNIFF = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'negocio',
    'productos',
    'pedidos',
    'gastos',
    'estadisticas',
    'antojo',
    'clientes',
]

# Token de DRF: sin esto las vistas quedarían con la autenticación por sesión solamente,
# que no sirve para el frontend separado.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Cerrado por defecto: cualquier endpoint nuevo que no declare permission_classes
    # propios queda solo para el staff logueado. Lo público (menú, config del sitio,
    # login, crear un pedido) se abre explícitamente en cada vista.
    'DEFAULT_PERMISSION_CLASSES': [
        'core.permissions.EsAdmin',
    ],
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['DB_NAME'],
            'USER': os.environ['DB_USER'],
            'PASSWORD': os.environ['DB_PASSWORD'],
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'CONN_MAX_AGE': 60,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Argentina/Cordoba'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Solo el frontend conocido puede llamar a la API (antes cualquier sitio podía).
CORS_ALLOWED_ORIGINS = [
    'https://tienda-ia-hamburguesa.vercel.app',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
# Cubre además los deploys de preview que arma Vercel automáticamente para este proyecto
# (ej. tienda-ia-hamburguesa-git-alguna-rama.vercel.app).
CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^https://tienda-ia-hamburguesa.*\.vercel\.app$',
]
CORS_ALLOWED_ORIGINS += [o.strip() for o in os.environ.get('CORS_EXTRA_ORIGINS', '').split(',') if o.strip()]

# En desarrollo, Vite cambia de puerto solo si el 5173 está ocupado (5174, 5175...).
# Sin esto, la API rechaza al frontend por CORS y todo falla con "Network Error".
# Solo aplica con DEBUG=True: en producción sigue valiendo únicamente la lista de arriba.
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES += [
        r'^http://localhost:\d+$',
        r'^http://127\.0\.0\.1:\d+$',
    ]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')