"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Variables de entorno: en local se leen de un archivo .env (no versionado) junto a
# manage.py; en PythonAnywhere se configuran en el panel de la app (ver README/chat).
load_dotenv(BASE_DIR / '.env')


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# SECURITY WARNING: keep the secret key used in production secret!
# El valor de acá abajo es solo un respaldo para que el proyecto no se rompa si falta
# el .env — en producción SIEMPRE tiene que estar seteado DJANGO_SECRET_KEY.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-ww(qv84a)bqrgav_fqesmg(yhod*hy*uhv32=%-spzeq1=#23z',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Por defecto queda APAGADO (seguro) a menos que el .env diga explícitamente lo contrario.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['www.odettiautomotores.online', 'odettiautomotores.online', 'webapp-3159337.pythonanywhere.com', 'localhost', '127.0.0.1']

# Endurecimiento de seguridad que solo aplica cuando DEBUG está apagado (producción) —
# en local (DEBUG=True) se dejan desactivados para no romper el runserver por http.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

SECURE_CONTENT_TYPE_NOSNIFF = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'negocio',
    'productos',
    'pedidos',
    'gastos',
    'estadisticas',
    'antojo',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Argentina/Cordoba'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Solo el frontend conocido puede llamar a la API (antes cualquier sitio podía).
CORS_ALLOWED_ORIGINS = [
    'https://tienda-ia-hamburguesa.vercel.app',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
# Cubre además los deploys de preview que arma Vercel automáticamente para este proyecto
# (ej. tienda-ia-hamburguesa-git-alguna-rama.vercel.app).
CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^https://tienda-ia-hamburguesa.*\.vercel\.app$',
]

# En desarrollo, Vite cambia de puerto solo si el 5173 está ocupado (5174, 5175...).
# Sin esto, la API rechaza al frontend por CORS y todo falla con "Network Error".
# Solo aplica con DEBUG=True: en producción sigue valiendo únicamente la lista de arriba.
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES += [
        r'^http://localhost:\d+$',
        r'^http://127\.0\.0\.1:\d+$',
    ]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')