# Generated by Django 6.0.7 on 2026-08-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recompensa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("puntos", models.PositiveIntegerField()),
                ("activa", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["puntos"],
            },
        ),
    ]
