# Generated by Django 6.0.7 on 2026-07-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sitio/logos/')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='sitio/portadas/')),
            ],
        ),
    ]
