# Generated by Django 6.0.7 on 2026-08-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0003_configuracionsitio_video_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='logo_precarga',
            field=models.ImageField(blank=True, help_text='Imagen que se muestra en la pantalla de carga inicial (recomendado: PNG sin fondo)', null=True, upload_to='sitio/logos/'),
        ),
    ]
