# Generated by Django 6.0.7 on 2026-08-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocio", "0004_configuracionsitio_logo_precarga"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionsitio",
            name="pesos_por_punto",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="configuracionsitio",
            name="valor_punto",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
