# Generated by Django 6.0.7 on 2026-08-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0005_configuracionsitio_pesos_por_punto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_acento',
            field=models.CharField(default='#e8630c', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_fondo',
            field=models.CharField(default='#0d2b23', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_navbar',
            field=models.CharField(default='#0d2b23', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_superficie',
            field=models.CharField(default='#163a30', max_length=7),
        ),
    ]
