# Generated by Django 6.0.7 on 2026-08-27 02:39

import negocio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0009_crear_usuario_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='permisos_empleado',
            field=models.JSONField(blank=True, default=negocio.models.permisos_empleado_default),
        ),
    ]
