# Generated by Django 6.0.7 on 2026-07-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionsitio",
            name="instagram",
            field=models.URLField(
                blank=True, default="https://www.instagram.com/antojoburger_/"
            ),
        ),
        migrations.AddField(
            model_name="configuracionsitio",
            name="whatsapp",
            field=models.CharField(blank=True, default="5493544400993", max_length=20),
        ),
    ]
