# Generated by Django 6.0.7 on 2026-08-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_configuracionsitio_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='video_principal',
            field=models.FileField(blank=True, help_text='Video de fondo para el inicio (Formato 9:16 recomendado)', null=True, upload_to='videos/'),
        ),
    ]
