# Generated by Django 6.0.7 on 2026-08-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0006_configuracionsitio_color_acento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_boton_agregar',
            field=models.CharField(default='#ffc700', max_length=7),
        ),
    ]
