# Generated by Django 6.0.7 on 2026-08-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0007_configuracionsitio_color_boton_agregar'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='mensaje_cerrado',
            field=models.CharField(blank=True, default='Volvemos pronto, gracias por tu paciencia.', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='tienda_abierta',
            field=models.BooleanField(default=True),
        ),
    ]
