# Generated by Django 6.0.7 on 2026-07-18 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Insumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("unidad", models.CharField(default="unidades", max_length=20)),
                (
                    "cantidad_disponible",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Gasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("insumos", "Insumos / Stock"),
                            ("servicios", "Servicios"),
                            ("sueldos", "Sueldos"),
                            ("otros", "Otros"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "cantidad",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "insumo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gastos",
                        to="gastos.insumo",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
    ]
