# Generated by Django 6.0.7 on 2026-08-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="insumo",
            name="stock_minimo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
