# Generated by Django 6.0.7 on 2026-08-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0002_insumo_stock_minimo"),
    ]

    operations = [
        migrations.CreateModel(
            name="GastoFijo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("insumos", "Insumos / Stock"),
                            ("servicios", "Servicios"),
                            ("sueldos", "Sueldos"),
                            ("otros", "Otros"),
                        ],
                        default="otros",
                        max_length=20,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("mensual", "Mensual"),
                            ("quincenal", "Quincenal"),
                            ("semanal", "Semanal"),
                        ],
                        default="mensual",
                        max_length=20,
                    ),
                ),
                ("proximo_vencimiento", models.DateField()),
                ("dias_aviso", models.PositiveIntegerField(default=5)),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["proximo_vencimiento"],
            },
        ),
    ]
