# Generated by Django 6.0.7 on 2026-08-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_insumo_descuento_hasta_insumo_descuento_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
