# Generated by Django 6.0.7 on 2026-09-06 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0006_insumo_precio'),
        ('pedidos', '0023_caja_efectivo_contado_pago_vuelto_metodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='pedidos.caja'),
        ),
    ]
