# Generated by Django 6.0.7 on 2026-09-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0007_gasto_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='sale_del_cajon',
            field=models.BooleanField(default=False),
        ),
    ]
