# Generated by Django 6.0.7 on 2026-09-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0009_marcar_gastos_de_cajon_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='costo_manual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
