# Generated by Django 6.0.7 on 2026-09-12 18:46

import django.db.models.deletion
from django.db import migrations, models


def saldo_al_empezar(apps, schema_editor):
    # Un movimiento de referencia por insumo con el stock que tenía al activar el
    # historial: así la lista arranca en un número conocido y no "de la nada".
    Insumo = apps.get_model('gastos', 'Insumo')
    MovimientoStock = apps.get_model('gastos', 'MovimientoStock')
    MovimientoStock.objects.bulk_create([
        MovimientoStock(insumo=i, tipo='inicial', cantidad=0, stock_resultante=i.cantidad_disponible,
                        detalle='Saldo al empezar el historial')
        for i in Insumo.objects.all()
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0010_insumo_costo_manual'),
        ('pedidos', '0024_movimientocaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inicial', 'Saldo inicial'), ('venta', 'Venta'), ('devolucion', 'Pedido cancelado o borrado'), ('compra', 'Compra'), ('compra_anulada', 'Compra borrada o corregida'), ('ajuste', 'Ajuste por recuento')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_resultante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='gastos.gasto')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gastos.insumo')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['-creado', '-id'],
            },
        ),
        migrations.RunPython(saldo_al_empezar, migrations.RunPython.noop),
    ]
