# Generated by Django 6.0.7 on 2026-07-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_producto_insumos"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="es_extra",
            field=models.BooleanField(default=False),
        ),
    ]
