# Generated by Django 6.0.7 on 2026-07-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_producto_es_extra"),
    ]

    operations = [
        migrations.CreateModel(
            name="Combo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="productos/combos/"
                    ),
                ),
                ("activo", models.BooleanField(default=False)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "productos",
                    models.ManyToManyField(
                        related_name="combos", to="productos.producto"
                    ),
                ),
            ],
            options={
                "ordering": ["-creado"],
            },
        ),
    ]
