# Generated by Django 6.0.7 on 2026-08-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0007_alter_combo_productos_alter_producto_insumos"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="descuento_hasta",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="descuento_pct",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
