# Generated by Django 6.0.7 on 2026-08-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_presentacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentacion',
            options={'ordering': ['precio']},
        ),
    ]
