# Generated by Django 6.0.7 on 2026-08-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_presentacioninsumo_presentacion_insumos_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
