# Generated by Django 6.0.1 on 2026-08-01 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0005_pedido_hora_salida"),
        ("productos", "0007_alter_combo_productos_alter_producto_insumos"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetalleExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "detalle_pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extras",
                        to="pedidos.detallepedido",
                    ),
                ),
                (
                    "extra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usado_como_extra",
                        to="productos.producto",
                    ),
                ),
            ],
        ),
    ]
