# Generated by Django 6.0.1 on 2026-08-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0006_detalleextra"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="nota",
            field=models.TextField(blank=True),
        ),
    ]
