# Generated by Django 6.0.1 on 2026-08-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0008_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleextra",
            name="cantidad",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
