# Generated by Django 6.0.7 on 2026-08-12 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_detallepedido_descuento_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abierta_en', models.DateTimeField(auto_now_add=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('nota_apertura', models.CharField(blank=True, max_length=200)),
                ('nota_cierre', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-abierta_en'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pedidos.caja'),
        ),
    ]
