# Generated by Django 6.0.7 on 2026-08-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_caja_pedido_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='confirmado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='origen',
            field=models.CharField(choices=[('web', 'Tienda web'), ('admin', 'Cargado manualmente')], default='admin', max_length=10),
        ),
    ]
