# Generated by Django 6.0.7 on 2026-08-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0016_detallepedido_sugerido_carrito"),
    ]

    operations = [
        migrations.AddField(
            model_name="caja",
            name="metodo_inicial",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("transferencia", "Transferencia"),
                    ("tarjeta_debito", "Tarjeta de débito"),
                    ("tarjeta_credito", "Tarjeta de crédito"),
                    ("mercado_pago", "Mercado Pago"),
                    ("otro", "Otro"),
                ],
                default="efectivo",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="caja",
            name="monto_inicial",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
