# Generated by Django 6.0.7 on 2026-08-18 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("pedidos", "0017_caja_metodo_inicial_caja_monto_inicial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="cliente_registrado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos",
                to="clientes.cliente",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="descuento_puntos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="pedido",
            name="puntos_acreditados",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pedido",
            name="puntos_usados",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
