# Generated by Django 6.0.7 on 2026-09-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0022_detalleextra_sugerido_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='efectivo_contado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='vuelto_metodo',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta_debito', 'Tarjeta de débito'), ('tarjeta_credito', 'Tarjeta de crédito'), ('mercado_pago', 'Mercado Pago'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='vuelto_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
