# Generated by Django 6.0.7 on 2026-09-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0024_movimientocaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='impreso',
            field=models.BooleanField(default=False),
        ),
    ]
