# Generated by Django 6.0.7 on 2026-07-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0001_initial"),
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="insumos",
            field=models.ManyToManyField(
                blank=True, related_name="productos", to="gastos.insumo"
            ),
        ),
    ]
