# Generated by Django 6.0.1 on 2026-07-31 18:34
# Editado a mano: Django no permite AlterField para agregar through= a un M2M
# (ValueError: "you cannot alter to or from M2M fields, or add or remove
# through= on M2M fields"), así que se reemplaza por RemoveField + AddField.
# Los datos ya fueron copiados a ProductoInsumo/ComboItem en la migración 0006.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0001_initial"),
        ("productos", "0006_copiar_insumos_y_productos_existentes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="combo",
            name="productos",
        ),
        migrations.AddField(
            model_name="combo",
            name="productos",
            field=models.ManyToManyField(
                related_name="combos",
                through="productos.ComboItem",
                to="productos.producto",
            ),
        ),
        migrations.RemoveField(
            model_name="producto",
            name="insumos",
        ),
        migrations.AddField(
            model_name="producto",
            name="insumos",
            field=models.ManyToManyField(
                blank=True,
                related_name="productos",
                through="productos.ProductoInsumo",
                to="gastos.insumo",
            ),
        ),
    ]
