# Generated by Django 6.0.7 on 2026-08-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_producto_descuento_hasta_producto_descuento_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento_carrito_pct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='sugerido_carrito',
            field=models.BooleanField(default=False),
        ),
    ]
