# Generated by Django 6.0.7 on 2026-08-19 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_insumo_descuento_hasta_insumo_descuento_pct'),
        ('productos', '0011_alter_presentacion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentacionInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_presentaciones', to='gastos.insumo')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_insumos_extra', to='productos.presentacion')),
            ],
            options={
                'unique_together': {('presentacion', 'insumo')},
            },
        ),
        migrations.AddField(
            model_name='presentacion',
            name='insumos_extra',
            field=models.ManyToManyField(blank=True, related_name='presentaciones_extra', through='productos.PresentacionInsumo', to='gastos.insumo'),
        ),
    ]
