# Generated by Django 6.0.7 on 2026-08-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0003_gastofijo"),
    ]

    operations = [
        migrations.AddField(
            model_name="gasto",
            name="metodo_pago",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("transferencia", "Transferencia"),
                    ("tarjeta_debito", "Tarjeta de débito"),
                    ("tarjeta_credito", "Tarjeta de crédito"),
                    ("mercado_pago", "Mercado Pago"),
                    ("otro", "Otro"),
                ],
                default="efectivo",
                max_length=20,
            ),
        ),
    ]
