# Generated by Django 6.0.7 on 2026-08-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_gasto_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='descuento_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='descuento_pct',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
